version: 2

jobs:
  build_and_test:
    docker:
      - image: circleci/python:2.7
      - image: rabbitmq:3
      - image: mongo:3.4

    working_directory: ~/repo

    environment:
      VIRTUALENV_DIR: "~/virtualenv"

    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
      - run:
          name: Download dependencies
          command: |
            git clone -b master git@github.com:stackstorm-exchange/ci.git ~/ci
            ~/ci/.circle/dependencies
      - run:
          name: Run tests
          command: ~/ci/.circle/test
      - save_cache:
          key: v1-dependency-cache-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip
            - ~/.apt-cache

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
