---
name: st2_chatops_configure_e2e_tests_with_slack
description: Setup the ChatOps end-to-end tests with the Slack hubot adapter
enabled: true
runner_type: remote-shell-script
entry_point: st2_chatops_configure_e2e_tests_with_slack.sh
parameters:
  sudo:
    type: boolean
    immutable: true
    default: true
