---
name: st2_package_test_timer_stable_u14
pack: "st2cd"
description: Run st2_package_test on timer for stable packages
enabled: false

trigger:
  parameters:
    delta: 4
    unit: hours
  type: core.st2.IntervalTimer

criteria: {}

action:
  ref: st2cd.st2_package_test
  parameters:
    hostname: st2-pkg-stable-u14
    distro: UBUNTU14
    release: stable
