---
name: st2_pkg_test_stable_rhel8
pack: st2cd
description: Test stable packages
# TODO: Enable once we have release a stable version that supports RHEL 8
enabled: false

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 6
    minute: 0
    second: 0

criteria: {}

action:
  ref: st2ci.st2_pkg_e2e_test
  parameters:
    hostname: st2-pkg-stable-el8
    distro: RHEL8
    pkg_env: production
    release: stable
    version: "3.1.0"
    chatops: true
