---
name: st2_pkg_e2e_test_timer_stable_rhel7
pack: "st2cd"
description: Run st2_pkg_e2e_test on timer for stable packages
enabled: true

trigger:
  parameters:
    delta: 4
    unit: hours
  type: core.st2.IntervalTimer

criteria: {}

action:
  ref: st2cd.st2_pkg_e2e_test
  parameters:
    hostname: st2-pkg-stable-el7
    distro: RHEL7
    pkg_env: production
    release: stable
