---
name: st2_pkg_test_stable_u18
pack: st2cd
description: Test stable packages
enabled: true

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 6
    minute: 0
    second: 0
    day_of_week: 2

criteria: {}

action:
  ref: st2ci.st2_pkg_e2e_test
  parameters:
    hostname: st2-pkg-stable-u18
    distro: UBUNTU18
    pkg_env: production
    release: stable
    version: "3.5.0"
    chatops: true
