---
name: st2_pkg_test_stable_u18_enterprise
pack: st2cd
description: Test stable packages
enabled: false

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 7
    minute: 0
    second: 0

criteria: {}

action:
  ref: st2ci.st2_pkg_e2e_test
  parameters:
    hostname: st2-ent-pkg-stable-u18
    distro: UBUNTU18
    pkg_env: production
    release: stable
    version: "3.2.0"
    enterprise: true
    enterprise_key: "{{st2kv.system.enterprise_key_prd_stable}}"
    chatops: true
