---
name: st2_pkg_test_stable_rhel7_enterprise
pack: st2cd
description: Test stable packages
enabled: true

trigger:
  type: core.st2.CronTimer
  parameters:
    timezone: US/Pacific
    hour: 7
    minute: 0
    second: 0

criteria: {}

action:
  ref: st2ci.st2_pkg_e2e_test
  parameters:
    hostname: st2-ent-pkg-stable-el7
    distro: RHEL7
    pkg_env: production
    release: stable
    version: "3.0.0"
    enterprise: true
    enterprise_key: "{{st2kv.system.enterprise_key_prd_stable}}"
